#Enable Upgraded Netherite compatibility
upgraded_netherite = true
#Enable Apotheosis compatibility
apotheosis = true
#Enable Forbidden and Arcanus compatibility
forbidden_arcanus = true

["Cold Sweat"]
	#Enable Cold Sweat Compatibility
	cold_sweat = true

	["Cold Sweat".CAVE]
		#Dragon Cold Resistance (Resistance against freezing damage and effects)
		#Range: 0.0 ~ 1.0
		cold_resistance = 0.0
		#Dragon Cold Dampening (Slows (negative values accelerate) the rate at of freezing)
		#Range: -1024.0 ~ 1.0
		cold_dampening = 0.0
		#Offset to the temperature threshold, after which a dragon's body temperature starts falling
		#Range: -1024.0 ~ 1024.0
		freezing_point = 0.0
		#Dragon Heat Resistance (Resistance against burning damage and effects)
		#Range: 0.0 ~ 1.0
		heat_resistance = 1.0
		#Dragon Heat Dampening (Slows (negative values accelerate) the rate at of overheating)
		#Range: -1024.0 ~ 1.0
		heat_dampening = 0.0
		#Offset to the temperature threshold, after which a dragon's body temperature starts rising
		#Range: -1024.0 ~ 1024.0
		burning_point = 0.0
		#Dragon Base Temperature (The body temperature (applied once)
		#Range: -150.0 ~ 150.0
		base_temperature = 0.0
		#Dragon World Temperature (The perceived world temperature)
		#Range: -1024.0 ~ 1024.0
		world_temperature = 0.0

	["Cold Sweat".SEA]
		#Dragon Cold Resistance (Resistance against freezing damage and effects)
		#Range: 0.0 ~ 1.0
		cold_resistance = 1.0
		#Dragon Cold Dampening (Slows (negative values accelerate) the rate at of freezing)
		#Range: -1024.0 ~ 1.0
		cold_dampening = 0.0
		#Offset to the temperature threshold, after which a dragon's body temperature starts falling
		#Range: -1024.0 ~ 1024.0
		freezing_point = 0.0
		#Dragon Heat Resistance (Resistance against burning damage and effects)
		#Range: 0.0 ~ 1.0
		heat_resistance = 0.0
		#Dragon Heat Dampening (Slows (negative values accelerate) the rate at of overheating)
		#Range: -1024.0 ~ 1.0
		heat_dampening = 0.0
		#Offset to the temperature threshold, after which a dragon's body temperature starts rising
		#Range: -1024.0 ~ 1024.0
		burning_point = 0.0
		#Dragon Base Temperature (The body temperature (applied once)
		#Range: -150.0 ~ 150.0
		base_temperature = 0.0
		#Dragon World Temperature (The perceived world temperature)
		#Range: -1024.0 ~ 1024.0
		world_temperature = 0.0

	["Cold Sweat".FOREST]
		#Dragon Cold Resistance (Resistance against freezing damage and effects)
		#Range: 0.0 ~ 1.0
		cold_resistance = 0.3
		#Dragon Cold Dampening (Slows (negative values accelerate) the rate at of freezing)
		#Range: -1024.0 ~ 1.0
		cold_dampening = 0.2
		#Offset to the temperature threshold, after which a dragon's body temperature starts falling
		#Range: -1024.0 ~ 1024.0
		freezing_point = 0.0
		#Dragon Heat Resistance (Resistance against burning damage and effects)
		#Range: 0.0 ~ 1.0
		heat_resistance = 0.3
		#Dragon Heat Dampening (Slows (negative values accelerate) the rate at of overheating)
		#Range: -1024.0 ~ 1.0
		heat_dampening = 0.2
		#Offset to the temperature threshold, after which a dragon's body temperature starts rising
		#Range: -1024.0 ~ 1024.0
		burning_point = 0.0
		#Dragon Base Temperature (The body temperature (applied once)
		#Range: -150.0 ~ 150.0
		base_temperature = 0.0
		#Dragon World Temperature (The perceived world temperature)
		#Range: -1024.0 ~ 1024.0
		world_temperature = 0.0

